In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

In [57]:
df = pd.read_csv(filepath_or_buffer= "../data/Extract_Dataset.csv") 
df

,Unnamed: 0,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,0,Untap,in.untap,Entertainment,3.9,68.0,"10,000+",10000.0,10291,True,...,https://untap.in,hello@untap.in,"Nov 2, 2020","Nov 02, 2020",Everyone,NaN,False,False,False,2021-06-16 11:24:00
1,1,Green Meadows,com.ooweboowebengineers.greenmeadows,Lifestyle,0.0,0.0,50+,50.0,90,True,...,http://ooweboo.co.za,ray@ooweboo.co.za,"May 29, 2017","May 29, 2017",Everyone,http://appmc2.net/privacy?company=OOWEBOO%20We...,False,False,False,2021-06-16 10:54:34
2,2,YG SELECT,com.makeshop.powerapp.ygnext,Shopping,4.3,918.0,"100,000+",100000.0,135038,True,...,http://www.ygeshop.com,app.ygselect@gmail.com,"Jan 20, 2016","May 12, 2021",Everyone,http://www.ygeshop.com/m/privacy.html,True,False,False,2021-06-16 02:21:54
3,3,Vinca Wealth,com.bag4wealth,Finance,5.0,6.0,50+,50.0,53,True,...,https://bag4wealth.com,acmatics.app@gmail.com,"Jun 30, 2020","May 11, 2021",Everyone,https://bag4wealth.com/finnsys/app/privacy.php,False,False,False,2021-06-16 01:29:59
4,4,Drink recipes,com.drinks.recipes,Food & Drink,4.3,830.0,"100,000+",100000.0,142498,True,...,http://cookwithlove.biz/,andrei.nazarco@gmail.com,"May 20, 2014","Jul 13, 2020",Everyone,http://cookwithlove.biz/privacy_policy/drink_r...,True,False,False,2021-06-16 08:43:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Deep Memorial Public School,com.edunext.dmps,Education,4.3,142.0,"1,000+",1000.0,2490,True,...,http://www.edunexttechnologies.com,edunexttech@gmail.com,"Mar 4, 2016","Aug 26, 2020",Everyone,http://www.edunexttechnologies.com/terms-and-c...,False,False,False,2021-06-16 00:56:34
9996,9996,Anchored Sins,com.goc.anchoredsins3D,Role Playing,NaN,NaN,5+,5.0,8,True,...,https://www.gearoverclocked.com/projects,gearoverclocked@gmail.com,NaN,"Jan 03, 2020",Teen,NaN,False,False,False,2021-06-16 02:44:16
9997,9997,설운도 트로트 노래모음,korea.singer.sulundo,Music & Audio,5.0,9.0,"1,000+",1000.0,1035,True,...,http://israng.co.kr,parkhanye28@gmail.com,"Apr 23, 2020","Feb 03, 2021",Teen,https://docs.google.com/document/d/1C6-LdIQzH7...,True,False,False,2021-06-16 12:40:44
9998,9998,Coq,fr.enfantdoudou.coq,Entertainment,0.0,0.0,500+,500.0,522,True,...,NaN,pridgua@gmail.com,"Apr 16, 2020","Apr 16, 2020",Everyone,https://www.ftc.gov/tips-advice/business-cente...,True,False,False,2021-06-16 12:06:11
9999,9999,Color Kraft,com.ekraft.colorkraft,Casual,4.9,19.0,500+,500.0,656,True,...,http://ekraft.co.in,dakshpandyaweb@gmail.com,"Apr 24, 2015","Dec 23, 2015",Everyone,http://ekraft.co.in/privacy.html,True,False,False,2021-06-15 22:07:22

We can see that there is an index column called Unnamed, we need to make the first column index the primary index

In [58]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Untap,in.untap,Entertainment,3.9,68.0,"10,000+",10000.0,10291,True,0.0,...,https://untap.in,hello@untap.in,"Nov 2, 2020","Nov 02, 2020",Everyone,NaN,False,False,False,2021-06-16 11:24:00
1,Green Meadows,com.ooweboowebengineers.greenmeadows,Lifestyle,0.0,0.0,50+,50.0,90,True,0.0,...,http://ooweboo.co.za,ray@ooweboo.co.za,"May 29, 2017","May 29, 2017",Everyone,http://appmc2.net/privacy?company=OOWEBOO%20We...,False,False,False,2021-06-16 10:54:34
2,YG SELECT,com.makeshop.powerapp.ygnext,Shopping,4.3,918.0,"100,000+",100000.0,135038,True,0.0,...,http://www.ygeshop.com,app.ygselect@gmail.com,"Jan 20, 2016","May 12, 2021",Everyone,http://www.ygeshop.com/m/privacy.html,True,False,False,2021-06-16 02:21:54
3,Vinca Wealth,com.bag4wealth,Finance,5.0,6.0,50+,50.0,53,True,0.0,...,https://bag4wealth.com,acmatics.app@gmail.com,"Jun 30, 2020","May 11, 2021",Everyone,https://bag4wealth.com/finnsys/app/privacy.php,False,False,False,2021-06-16 01:29:59
4,Drink recipes,com.drinks.recipes,Food & Drink,4.3,830.0,"100,000+",100000.0,142498,True,0.0,...,http://cookwithlove.biz/,andrei.nazarco@gmail.com,"May 20, 2014","Jul 13, 2020",Everyone,http://cookwithlove.biz/privacy_policy/drink_r...,True,False,False,2021-06-16 08:43:51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Deep Memorial Public School,com.edunext.dmps,Education,4.3,142.0,"1,000+",1000.0,2490,True,0.0,...,http://www.edunexttechnologies.com,edunexttech@gmail.com,"Mar 4, 2016","Aug 26, 2020",Everyone,http://www.edunexttechnologies.com/terms-and-c...,False,False,False,2021-06-16 00:56:34
9996,Anchored Sins,com.goc.anchoredsins3D,Role Playing,NaN,NaN,5+,5.0,8,True,0.0,...,https://www.gearoverclocked.com/projects,gearoverclocked@gmail.com,NaN,"Jan 03, 2020",Teen,NaN,False,False,False,2021-06-16 02:44:16
9997,설운도 트로트 노래모음,korea.singer.sulundo,Music & Audio,5.0,9.0,"1,000+",1000.0,1035,True,0.0,...,http://israng.co.kr,parkhanye28@gmail.com,"Apr 23, 2020","Feb 03, 2021",Teen,https://docs.google.com/document/d/1C6-LdIQzH7...,True,False,False,2021-06-16 12:40:44
9998,Coq,fr.enfantdoudou.coq,Entertainment,0.0,0.0,500+,500.0,522,True,0.0,...,NaN,pridgua@gmail.com,"Apr 16, 2020","Apr 16, 2020",Everyone,https://www.ftc.gov/tips-advice/business-cente...,True,False,False,2021-06-16 12:06:11
9999,Color Kraft,com.ekraft.colorkraft,Casual,4.9,19.0,500+,500.0,656,True,0.0,...,http://ekraft.co.in,dakshpandyaweb@gmail.com,"Apr 24, 2015","Dec 23, 2015",Everyone,http://ekraft.co.in/privacy.html,True,False,False,2021-06-15 22:07:22

### Data Dictionnary
This is a data dictionnary for the project. It contains all the information about the dataset used to train and test the model.

App Name:

    - object 
    - The name of the application on the Google play store 
    - 
App Id: 

    - object
    - The application have an unique identifiers
    -  
Category: 

    - object
    - The application belong to a specific category 
    - 
Rating: 

    - float64
    -  This is the average rating for an application  
    - 
Rating Count:

    - float64
    - the number of person that rate the application   
    - 
Installs:

    - object
    -  the approximate number of install of the app
    -            
Minimum Installs:

    - float64
    -   
    -    
Maximum Installs

    - int64  
    -   
    -    
Free: 

    - bool
    - The application doesnt cost 
    -                 
Price:

    - float64
    -   The cost of the mobile application 
    -               
Currency:

    - object
    - The currency in which the price of the mobile application is listed
    -           
Size:

    - object
    - The size of the mobile application in terms of storage space 
    -               
Minimum Android:

    - object
    -  The minimum version of the Android operating system required to run the mobile application.
    -      
Developer Id:

    - object
    -  The developer has a unique identifier
    -         
Developer Website:

    - object
    - The website associated with the developer or company behind the mobile application 
    -   
Developer Email: 

    - object
    -  The email address of the developer or company responsible for the mobile application.
    -     
Released:    

    - object
    -   The date when the mobile application was initially released on the Google Play Store.
    -           
Last Updated: 

    - object
    -  The date when the mobile application was last updated 
    -       
Content Rating:

    - object
    - The content rating for which the mobile application is suitable
    -      
Privacy Policy:

    - object
    -  A link to the privacy policy associated with the mobile application.
    -      
Editors Choice:

    - bool
    -  the mobile application has been selected as an "Editor's Choice" on the Google Play Store.
    -   
Scraped Time:
 
    - object
    -  The date where the data was collected in the google play store
    -

### Step 1: Check datatypes and format

In [59]:
df.shape

(10000, 24)

This DataFrame contains 10000 rows and 24 columns

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   App Name           10000 non-null  object
 1   App Id             10000 non-null  object
 2   Category           10000 non-null  object
 3   Rating             9906 non-null   float64
 4   Rating Count       9906 non-null   float64
 5   Installs           9999 non-null   object
 6   Minimum Installs   9999 non-null   float64
 7   Maximum Installs   10000 non-null  int64
 8   Free               10000 non-null  bool
 9   Price              10000 non-null  float64
 10  Currency           9999 non-null   object
 11  Size               9999 non-null   object
 12  Minimum Android    9969 non-null   object
 13  Developer Id       10000 non-null  object
 14  Developer Website  6628 non-null   object
 15  Developer Email    10000 non-null  object
 16  Released           9694 non-null   object
 17  Last Updated       10000 non-null  object
 18  Content Rating     10000 non-null  object
 19  Privacy Policy     8254 non-null   object
 20  Ad Supported       10000 non-null  bool
 21  In App Purchases   10000 non-null  bool
 22  Editors Choice     10000 non-null  bool
 23  Scraped Time       10000 non-null  object
dtypes: bool(4), float64(4), int64(1), object(15)
memory usage: 1.6+ MB

We can that see there are a mixture of numerical and categorical columns. There is lots of "object" type which corresponds to categorical data. We can also see that there is boolean data that might be some binary type columns which could be True/False or 0/1 which are captured as "yes"/"no". Finally, we see that there are some columns missing data in Rating, Rating Count ,Installs, Minimum Installs, Currency, Size, Minimum Android, Developer Website (this columns has the more null value compare to the other columns), Released and Privacy Policy.

### Dropping Columns

In [61]:

df.drop(columns = ['Last Updated','App Name','Size','Minimum Android','Minimum Installs', 'App Id', 'Currency', 'Developer Website', 'Privacy Policy', 'Scraped Time', 'Developer Email', 'Developer Id', 'Installs', 'Released', 'Maximum Installs'], inplace= True)

C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\2811287325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ['Last Updated','App Name','Size','Minimum Android','Minimum Installs', 'App Id', 'Currency', 'Developer Website', 'Privacy Policy', 'Scraped Time', 'Developer Email', 'Developer Id', 'Installs', 'Released', 'Maximum Installs'], inplace= True)

We decided to drop those columns as they were not in use for our prediction analysis

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          10000 non-null  object
 1   Rating            9906 non-null   float64
 2   Rating Count      9906 non-null   float64
 3   Free              10000 non-null  bool
 4   Price             10000 non-null  float64
 5   Content Rating    10000 non-null  object
 6   Ad Supported      10000 non-null  bool
 7   In App Purchases  10000 non-null  bool
 8   Editors Choice    10000 non-null  bool
dtypes: bool(4), float64(3), object(2)
memory usage: 429.8+ KB

### Checking for duplicate data

In [63]:
df.duplicated().sum()

4553

There is some duplicated data, we will check with the percententage of duplicated values based on the dataframe shape

In [64]:
df.duplicated().sum()/df.shape[0]*100

45.53

In [70]:
df.drop_duplicates(inplace= True)

C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\2207841240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace= True)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5447 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          5447 non-null   object
 1   Rating            5390 non-null   float64
 2   Rating Count      5390 non-null   float64
 3   Free              5447 non-null   bool
 4   Price             5447 non-null   float64
 5   Content Rating    5447 non-null   object
 6   Ad Supported      5447 non-null   bool
 7   In App Purchases  5447 non-null   bool
 8   Editors Choice    5447 non-null   bool
dtypes: bool(4), float64(3), object(2)
memory usage: 276.6+ KB

In [73]:
df.T.duplicated().sum()

0

According to this command there is no ducplicate information

### Dealing with missing data

In [74]:
df.isna().sum()

Category             0
Rating              57
Rating Count        57
Free                 0
Price                0
Content Rating       0
Ad Supported         0
In App Purchases     0
Editors Choice       0
dtype: int64

In [75]:
df.isna().sum()/df.shape[0]*100

Category            0.000000
Rating              1.046448
Rating Count        1.046448
Free                0.000000
Price               0.000000
Content Rating      0.000000
Ad Supported        0.000000
In App Purchases    0.000000
Editors Choice      0.000000
dtype: float64

We can see that there is few missing values. 
It is a small portion of the columns so we can drop the null values.

In [76]:
df.dropna(inplace = True)

C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\1791587065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace = True)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5390 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          5390 non-null   object
 1   Rating            5390 non-null   float64
 2   Rating Count      5390 non-null   float64
 3   Free              5390 non-null   bool
 4   Price             5390 non-null   float64
 5   Content Rating    5390 non-null   object
 6   Ad Supported      5390 non-null   bool
 7   In App Purchases  5390 non-null   bool
 8   Editors Choice    5390 non-null   bool
dtypes: bool(4), float64(3), object(2)
memory usage: 273.7+ KB

### Changing some values into binary

In [78]:
df

,Category,Rating,Rating Count,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Entertainment,3.9,68.0,True,0.0,Everyone,False,False,False
1,Lifestyle,0.0,0.0,True,0.0,Everyone,False,False,False
2,Shopping,4.3,918.0,True,0.0,Everyone,True,False,False
3,Finance,5.0,6.0,True,0.0,Everyone,False,False,False
4,Food & Drink,4.3,830.0,True,0.0,Everyone,True,False,False
...,...,...,...,...,...,...,...,...,...
9992,Video Players & Editors,2.5,6.0,True,0.0,Everyone,True,False,False
9993,Music & Audio,5.0,17.0,True,0.0,Everyone,True,False,False
9995,Education,4.3,142.0,True,0.0,Everyone,False,False,False
9997,Music & Audio,5.0,9.0,True,0.0,Teen,True,False,False
9999,Casual,4.9,19.0,True,0.0,Everyone,True,False,False

To be able to change some of our values into binary we need to change the datatype in integer

In [79]:
df["Free"] = df["Free"].astype(int)
df["In App Purchases"] = df["In App Purchases"].astype(int)
df["Editors Choice"] = df["Editors Choice"].astype(int)
df["Ad Supported"] = df["Ad Supported"].astype(int)

C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\860087706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Free"] = df["Free"].astype(int)
C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\860087706.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["In App Purchases"] = df["In App Purchases"].astype(int)
C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\860087706.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Editors Choice"] = df["Editors Choice"].astype(int)
C:\Users\lelon\AppData\Local\Temp\ipykernel_1032\860087706.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ad Supported"] = df["Ad Supported"].astype(int)

we now can check if the datatype change was effective by using .info()

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5390 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          5390 non-null   object
 1   Rating            5390 non-null   float64
 2   Rating Count      5390 non-null   float64
 3   Free              5390 non-null   int32
 4   Price             5390 non-null   float64
 5   Content Rating    5390 non-null   object
 6   Ad Supported      5390 non-null   int32
 7   In App Purchases  5390 non-null   int32
 8   Editors Choice    5390 non-null   int32
dtypes: float64(3), int32(4), object(2)
memory usage: 336.9+ KB

In [81]:
df.head()

,Category,Rating,Rating Count,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Entertainment,3.9,68.0,1,0.0,Everyone,0,0,0
1,Lifestyle,0.0,0.0,1,0.0,Everyone,0,0,0
2,Shopping,4.3,918.0,1,0.0,Everyone,1,0,0
3,Finance,5.0,6.0,1,0.0,Everyone,0,0,0
4,Food & Drink,4.3,830.0,1,0.0,Everyone,1,0,0

we can now tranfrom change some of our data into binary by transforming True into 1 and False into 0

In [82]:
df

,Category,Rating,Rating Count,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Entertainment,3.9,68.0,1,0.0,Everyone,0,0,0
1,Lifestyle,0.0,0.0,1,0.0,Everyone,0,0,0
2,Shopping,4.3,918.0,1,0.0,Everyone,1,0,0
3,Finance,5.0,6.0,1,0.0,Everyone,0,0,0
4,Food & Drink,4.3,830.0,1,0.0,Everyone,1,0,0
...,...,...,...,...,...,...,...,...,...
9992,Video Players & Editors,2.5,6.0,1,0.0,Everyone,1,0,0
9993,Music & Audio,5.0,17.0,1,0.0,Everyone,1,0,0
9995,Education,4.3,142.0,1,0.0,Everyone,0,0,0
9997,Music & Audio,5.0,9.0,1,0.0,Teen,1,0,0
9999,Casual,4.9,19.0,1,0.0,Everyone,1,0,0

In [83]:
df.to_csv('../data/Clean_Dataset2.csv', index = False)