In [1]:
import pandas as pd

In [9]:
df_clean = pd.read_csv(filepath_or_buffer= "../data/Clean_Dataset.csv") 
df_clean.head()

,Category,Rating,Rating Count,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Entertainment,3.9,68.0,1,0.0,Everyone,0,0,0
1,Lifestyle,0.0,0.0,1,0.0,Everyone,0,0,0
2,Shopping,4.3,918.0,1,0.0,Everyone,1,0,0
3,Finance,5.0,6.0,1,0.0,Everyone,0,0,0
4,Food & Drink,4.3,830.0,1,0.0,Everyone,1,0,0

### Dummies

In [3]:
df_clean['Category'].nunique()

48

In [4]:
df_clean['Editors Choice'].value_counts()

Editors Choice
0    9662
1       1
Name: count, dtype: int64

In [5]:
dummies = pd.get_dummies(df_clean['Category'], prefix = 'Category', dtype= int) 
df_clean = pd.concat([df_clean, dummies], axis=1)
df_clean = df_clean.drop('Category', axis=1)
df_clean

,Rating,Rating Count,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice,Category_Action,Category_Adventure,...,Category_Simulation,Category_Social,Category_Sports,Category_Strategy,Category_Tools,Category_Travel & Local,Category_Trivia,Category_Video Players & Editors,Category_Weather,Category_Word
0,3.9,68.0,1,0.0,Everyone,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.0,1,0.0,Everyone,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.3,918.0,1,0.0,Everyone,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5.0,6.0,1,0.0,Everyone,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.3,830.0,1,0.0,Everyone,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9658,0.0,0.0,1,0.0,Everyone,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9659,4.3,142.0,1,0.0,Everyone,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9660,5.0,9.0,1,0.0,Teen,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9661,0.0,0.0,1,0.0,Everyone,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9662,4.9,19.0,1,0.0,Everyone,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
dummies = pd.get_dummies(df_clean['Content Rating'], prefix = 'Content_Rating', dtype= int) 
df_clean = pd.concat([df_clean, dummies], axis=1)
df_clean = df_clean.drop('Content Rating', axis=1)
df_clean

,Rating,Rating Count,Free,Price,Ad Supported,In App Purchases,Editors Choice,Category_Action,Category_Adventure,Category_Arcade,...,Category_Trivia,Category_Video Players & Editors,Category_Weather,Category_Word,Content_Rating_Adults only 18+,Content_Rating_Everyone,Content_Rating_Everyone 10+,Content_Rating_Mature 17+,Content_Rating_Teen,Content_Rating_Unrated
0,3.9,68.0,1,0.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.0,0.0,1,0.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,4.3,918.0,1,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,5.0,6.0,1,0.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,4.3,830.0,1,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9658,0.0,0.0,1,0.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9659,4.3,142.0,1,0.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9660,5.0,9.0,1,0.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9661,0.0,0.0,1,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9662,4.9,19.0,1,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [7]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9663 entries, 0 to 9662
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rating                            9663 non-null   float64
 1   Rating Count                      9663 non-null   float64
 2   Free                              9663 non-null   int64
 3   Price                             9663 non-null   float64
 4   Ad Supported                      9663 non-null   int64
 5   In App Purchases                  9663 non-null   int64
 6   Editors Choice                    9663 non-null   int64
 7   Category_Action                   9663 non-null   int32
 8   Category_Adventure                9663 non-null   int32
 9   Category_Arcade                   9663 non-null   int32
 10  Category_Art & Design             9663 non-null   int32
 11  Category_Auto & Vehicles          9663 non-null   int32
 12  Category_Beauty                   9663 non-null   int32
 13  Category_Board                    9663 non-null   int32
 14  Category_Books & Reference        9663 non-null   int32
 15  Category_Business                 9663 non-null   int32
 16  Category_Card                     9663 non-null   int32
 17  Category_Casino                   9663 non-null   int32
 18  Category_Casual                   9663 non-null   int32
 19  Category_Comics                   9663 non-null   int32
 20  Category_Communication            9663 non-null   int32
 21  Category_Dating                   9663 non-null   int32
 22  Category_Education                9663 non-null   int32
 23  Category_Educational              9663 non-null   int32
 24  Category_Entertainment            9663 non-null   int32
 25  Category_Events                   9663 non-null   int32
 26  Category_Finance                  9663 non-null   int32
 27  Category_Food & Drink             9663 non-null   int32
 28  Category_Health & Fitness         9663 non-null   int32
 29  Category_House & Home             9663 non-null   int32
 30  Category_Libraries & Demo         9663 non-null   int32
 31  Category_Lifestyle                9663 non-null   int32
 32  Category_Maps & Navigation        9663 non-null   int32
 33  Category_Medical                  9663 non-null   int32
 34  Category_Music                    9663 non-null   int32
 35  Category_Music & Audio            9663 non-null   int32
 36  Category_News & Magazines         9663 non-null   int32
 37  Category_Parenting                9663 non-null   int32
 38  Category_Personalization          9663 non-null   int32
 39  Category_Photography              9663 non-null   int32
 40  Category_Productivity             9663 non-null   int32
 41  Category_Puzzle                   9663 non-null   int32
 42  Category_Racing                   9663 non-null   int32
 43  Category_Role Playing             9663 non-null   int32
 44  Category_Shopping                 9663 non-null   int32
 45  Category_Simulation               9663 non-null   int32
 46  Category_Social                   9663 non-null   int32
 47  Category_Sports                   9663 non-null   int32
 48  Category_Strategy                 9663 non-null   int32
 49  Category_Tools                    9663 non-null   int32
 50  Category_Travel & Local           9663 non-null   int32
 51  Category_Trivia                   9663 non-null   int32
 52  Category_Video Players & Editors  9663 non-null   int32
 53  Category_Weather                  9663 non-null   int32
 54  Category_Word                     9663 non-null   int32
 55  Content_Rating_Adults only 18+    9663 non-null   int32
 56  Content_Rating_Everyone           9663 non-null   int32
 57  Content_Rating_Everyone 10+       9663 non-null   int32
 58  Content_Rating_Mature 17+         9663 non-null   int32
 59  Content_Rating_Teen               9663 non-null   int32
 60  Content_Rating_Unrated            9663 non-null   int32
dtypes: float64(3), int32(54), int64(4)
memory usage: 2.5 MB

In [8]:
df_clean.to_csv('../data/Dataset_for_modeling.csv', index= False)