In [13]:
import pandas as pd

In [14]:
df_clean = pd.read_csv(filepath_or_buffer= "../data/Clean_Dataset.csv") 
df_clean

,Category,Rating,Rating Count,Minimum Installs,Maximum Installs,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Entertainment,3.9,68.0,10000.0,10291,1,0.0,Everyone,0,0,0
1,Lifestyle,0.0,0.0,50.0,90,1,0.0,Everyone,0,0,0
2,Shopping,4.3,918.0,100000.0,135038,1,0.0,Everyone,1,0,0
3,Finance,5.0,6.0,50.0,53,1,0.0,Everyone,0,0,0
4,Food & Drink,4.3,830.0,100000.0,142498,1,0.0,Everyone,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9901,Music,0.0,0.0,10.0,14,1,0.0,Everyone,0,0,0
9902,Education,4.3,142.0,1000.0,2490,1,0.0,Everyone,0,0,0
9903,Music & Audio,5.0,9.0,1000.0,1035,1,0.0,Teen,1,0,0
9904,Entertainment,0.0,0.0,500.0,522,1,0.0,Everyone,1,0,0
9905,Casual,4.9,19.0,500.0,656,1,0.0,Everyone,1,0,0

### Dummies

In [15]:
df_clean['Category'].nunique()

48

In [16]:
df_clean['Editors Choice'].value_counts()

Editors Choice
0    9905
1       1
Name: count, dtype: int64

In [17]:
dummies = pd.get_dummies(df_clean['Category'], prefix = 'Category', dtype= int) 
df_clean = pd.concat([df_clean, dummies], axis=1)
df_clean = df_clean.drop('Category', axis=1)
df_clean

,Rating,Rating Count,Minimum Installs,Maximum Installs,Free,Price,Content Rating,Ad Supported,In App Purchases,Editors Choice,...,Category_Simulation,Category_Social,Category_Sports,Category_Strategy,Category_Tools,Category_Travel & Local,Category_Trivia,Category_Video Players & Editors,Category_Weather,Category_Word
0,3.9,68.0,10000.0,10291,1,0.0,Everyone,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.0,50.0,90,1,0.0,Everyone,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.3,918.0,100000.0,135038,1,0.0,Everyone,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5.0,6.0,50.0,53,1,0.0,Everyone,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.3,830.0,100000.0,142498,1,0.0,Everyone,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,0.0,0.0,10.0,14,1,0.0,Everyone,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9902,4.3,142.0,1000.0,2490,1,0.0,Everyone,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9903,5.0,9.0,1000.0,1035,1,0.0,Teen,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9904,0.0,0.0,500.0,522,1,0.0,Everyone,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9905,4.9,19.0,500.0,656,1,0.0,Everyone,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
dummies = pd.get_dummies(df_clean['Content Rating'], prefix = 'Content_Rating', dtype= int) 
df_clean = pd.concat([df_clean, dummies], axis=1)
df_clean = df_clean.drop('Content Rating', axis=1)
df_clean

,Rating,Rating Count,Minimum Installs,Maximum Installs,Free,Price,Ad Supported,In App Purchases,Editors Choice,Category_Action,...,Category_Trivia,Category_Video Players & Editors,Category_Weather,Category_Word,Content_Rating_Adults only 18+,Content_Rating_Everyone,Content_Rating_Everyone 10+,Content_Rating_Mature 17+,Content_Rating_Teen,Content_Rating_Unrated
0,3.9,68.0,10000.0,10291,1,0.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.0,0.0,50.0,90,1,0.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,4.3,918.0,100000.0,135038,1,0.0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,5.0,6.0,50.0,53,1,0.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,4.3,830.0,100000.0,142498,1,0.0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,0.0,0.0,10.0,14,1,0.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9902,4.3,142.0,1000.0,2490,1,0.0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9903,5.0,9.0,1000.0,1035,1,0.0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9904,0.0,0.0,500.0,522,1,0.0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9905,4.9,19.0,500.0,656,1,0.0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [19]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9906 entries, 0 to 9905
Data columns (total 63 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rating                            9906 non-null   float64
 1   Rating Count                      9906 non-null   float64
 2   Minimum Installs                  9906 non-null   float64
 3   Maximum Installs                  9906 non-null   int64
 4   Free                              9906 non-null   int64
 5   Price                             9906 non-null   float64
 6   Ad Supported                      9906 non-null   int64
 7   In App Purchases                  9906 non-null   int64
 8   Editors Choice                    9906 non-null   int64
 9   Category_Action                   9906 non-null   int32
 10  Category_Adventure                9906 non-null   int32
 11  Category_Arcade                   9906 non-null   int32
 12  Category_Art & Design             9906 non-null   int32
 13  Category_Auto & Vehicles          9906 non-null   int32
 14  Category_Beauty                   9906 non-null   int32
 15  Category_Board                    9906 non-null   int32
 16  Category_Books & Reference        9906 non-null   int32
 17  Category_Business                 9906 non-null   int32
 18  Category_Card                     9906 non-null   int32
 19  Category_Casino                   9906 non-null   int32
 20  Category_Casual                   9906 non-null   int32
 21  Category_Comics                   9906 non-null   int32
 22  Category_Communication            9906 non-null   int32
 23  Category_Dating                   9906 non-null   int32
 24  Category_Education                9906 non-null   int32
 25  Category_Educational              9906 non-null   int32
 26  Category_Entertainment            9906 non-null   int32
 27  Category_Events                   9906 non-null   int32
 28  Category_Finance                  9906 non-null   int32
 29  Category_Food & Drink             9906 non-null   int32
 30  Category_Health & Fitness         9906 non-null   int32
 31  Category_House & Home             9906 non-null   int32
 32  Category_Libraries & Demo         9906 non-null   int32
 33  Category_Lifestyle                9906 non-null   int32
 34  Category_Maps & Navigation        9906 non-null   int32
 35  Category_Medical                  9906 non-null   int32
 36  Category_Music                    9906 non-null   int32
 37  Category_Music & Audio            9906 non-null   int32
 38  Category_News & Magazines         9906 non-null   int32
 39  Category_Parenting                9906 non-null   int32
 40  Category_Personalization          9906 non-null   int32
 41  Category_Photography              9906 non-null   int32
 42  Category_Productivity             9906 non-null   int32
 43  Category_Puzzle                   9906 non-null   int32
 44  Category_Racing                   9906 non-null   int32
 45  Category_Role Playing             9906 non-null   int32
 46  Category_Shopping                 9906 non-null   int32
 47  Category_Simulation               9906 non-null   int32
 48  Category_Social                   9906 non-null   int32
 49  Category_Sports                   9906 non-null   int32
 50  Category_Strategy                 9906 non-null   int32
 51  Category_Tools                    9906 non-null   int32
 52  Category_Travel & Local           9906 non-null   int32
 53  Category_Trivia                   9906 non-null   int32
 54  Category_Video Players & Editors  9906 non-null   int32
 55  Category_Weather                  9906 non-null   int32
 56  Category_Word                     9906 non-null   int32
 57  Content_Rating_Adults only 18+    9906 non-null   int32
 58  Content_Rating_Everyone           9906 non-null   int32
 59  Content_Rating_Everyone 10+       9906 non-null   int32
 60  Content_Rating_Mature 17+         9906 non-null   int32
 61  Content_Rating_Teen               9906 non-null   int32
 62  Content_Rating_Unrated            9906 non-null   int32
dtypes: float64(4), int32(54), int64(5)
memory usage: 2.7 MB

In [21]:
df_clean.to_csv('../data/Dataset_for_modeling.csv', index= False)